spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://localhost:3305/fornecedor
    username: root
    password: 260423
    driver-class-name: com.mysql.cj.jdbc.Driver
